
image: maven:3.5.4

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar
